version: '3'
services:
  service1:
    build: ./service1/
    command: node index.js
    networks:
      - service
  service2:
    build: ./service2/
    command: node index.js
    networks:
      - service
  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - service1
      - service2
    links:
      - service1
      - service2
    networks:
      - service
networks:
  servicer
